---
- name: Gluster installation playbook
  hosts: server*
  connection: smart
  
  tasks:

    - name: Install necessary packages
      yum:
        name: "{{item}}"
        state: installed
        disable_gpg_check: true
      with_items:
        - git
        - epel-release
        - centos-release-gluster38

    - name: Install Gluster Server components
      yum:
        name: "{{item}}"
        state: installed
        disable_gpg_check: true
      with_items:
        - samba
        - glusterfs-server
        - glusterfs-rdma

    - name: Enable and start glusterd
      service:
        name: glusterd
        enabled: yes
        state: started
