---
- name: Gluster Firewall playbook
  hosts: server*
  connection: smart
  
  tasks:
    - name: Enable and start firewalld
      service:
        name: firewalld
        enabled: yes
        state: started

    - name: Set up firewalld to use gluster
      firewalld:
        service: glusterfs
        permanent: true
        state: enabled

    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted